/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author varsh
 */
public class AddSupplier extends javax.swing.JFrame {
    
    String url,uname,pass;
    Connection con;
    Statement st;
    PreparedStatement pst;
    String query,update;

    /**
     * Creates new form AddSupplier
     */
    public AddSupplier() {
        initComponents();
        try{
            url = "jdbc:mysql://localhost:3306/pharmacy?autoReconnect=true&useSSL=false";
            uname = "root";
            pass = "password";
            con = DriverManager.getConnection(url,uname,pass);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e); 
          }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        supSubmitBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        sidTxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        snameTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        sphoneTxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        sAddrTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pharmacy Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Add New Supplier");

        supSubmitBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        supSubmitBtn.setText("Submit");
        supSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supSubmitBtnActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setText("Supplier ID");

        sidTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sidTxt.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setText("Supplier Name");

        snameTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setText("Phone No");

        sphoneTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setText("Address");

        sAddrTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(snameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sAddrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sphoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(supSubmitBtn)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel8)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(sidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sphoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(sAddrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(supSubmitBtn)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supSubmitBtnActionPerformed
        // TODO add your handling code here:
        if(sidTxt.getText().isEmpty() || snameTxt.getText().isEmpty() || sAddrTxt.getText().isEmpty()
            || sphoneTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All details are mandatory!");
        }
        else{
            try{
                update = "INSERT INTO supplier (sid,s_name,s_phone,s_address) VALUES (?,?,?,?);";
                pst = con.prepareStatement(update);
                pst.setString(1, sidTxt.getText());
                pst.setString(2, snameTxt.getText());
                pst.setString(3, sphoneTxt.getText());
                pst.setString(4, sAddrTxt.getText());
                int status = pst.executeUpdate();
                if(status>0){
                    JOptionPane.showMessageDialog(rootPane, "Successfully added a new Supplier", "Success", JOptionPane.INFORMATION_MESSAGE);
                    AddSupplier.this.dispose();
                }
                else
                JOptionPane.showMessageDialog(rootPane, "Could not add the Supplier", "Failed", JOptionPane.ERROR_MESSAGE);
            }
            catch(SQLIntegrityConstraintViolationException e){
                JOptionPane.showMessageDialog(null,"A supplier already exists with this Supplier ID");
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_supSubmitBtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField sAddrTxt;
    private javax.swing.JTextField sidTxt;
    private javax.swing.JTextField snameTxt;
    private javax.swing.JTextField sphoneTxt;
    private javax.swing.JButton supSubmitBtn;
    // End of variables declaration//GEN-END:variables
}
