package pharmacy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author varsh
 */
public class Modify extends javax.swing.JFrame {

    String url,uname,pass;
    Connection con;
    Statement st,st2;
    PreparedStatement pst;
    String query,query2,update;
    ResultSet rs,rs2;
    
    DefaultTableModel model1,model2,model3;
    /**
     * Creates new form Modify
     */
    
    public Modify() {
        initComponents();
        model1 =(DefaultTableModel) jTable1.getModel();
        model2 =(DefaultTableModel) jTable2.getModel();
        model3 = (DefaultTableModel) jTable3.getModel();
        try{
            url = "jdbc:mysql://localhost:3306/pharmacy?autoReconnect=true&useSSL=false";
            uname = "root";
            pass = "password";
            con = DriverManager.getConnection(url,uname,pass);
            st = con.createStatement();
            st2 = con.createStatement();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e); 
          }  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pidTxt = new javax.swing.JTextField();
        pnameTxt = new javax.swing.JTextField();
        stockTxt = new javax.swing.JTextField();
        priceTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addProductBtn = new javax.swing.JButton();
        catCombo = new javax.swing.JComboBox<>();
        deleteProdBtn = new javax.swing.JButton();
        updateProdBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rackTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addEmpBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        enameTxt = new javax.swing.JTextField();
        ephoneTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        salaryTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        eidTxt = new javax.swing.JTextField();
        desigTxt = new javax.swing.JTextField();
        updateEmpBtn = new javax.swing.JButton();
        deleteEmpBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        sAddrTxt = new javax.swing.JTextField();
        sidTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sphoneTxt = new javax.swing.JTextField();
        snameTxt = new javax.swing.JTextField();
        addSupBtn = new javax.swing.JButton();
        deleteSupBtn = new javax.swing.JButton();
        updateSupBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pharmacy Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1250, 1020));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTabbedPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1220, 1030));

        jPanel1.setPreferredSize(new java.awt.Dimension(1220, 1030));

        jTable1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine ID", "Medicine Name", "Type", "Rack", "Stock Available", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setRowHeight(22);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(430);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        pidTxt.setEditable(false);
        pidTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pidTxt.setToolTipText("Product ID can't be modified");

        pnameTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        stockTxt.setEditable(false);
        stockTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        stockTxt.setToolTipText("Stock  can't be modified");

        priceTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Medicine Name");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Type");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Stock");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Price");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Medicine ID");

        addProductBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addProductBtn.setText("Add New Medicine");
        addProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductBtnActionPerformed(evt);
            }
        });

        catCombo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        catCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablets", "Syrup", "Pills", "Injection", "Cream / Ointment", "Others" }));

        deleteProdBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deleteProdBtn.setText("Delete Medicine");
        deleteProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProdBtnActionPerformed(evt);
            }
        });

        updateProdBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        updateProdBtn.setText("Update Medicine");
        updateProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProdBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Update / Delete selected Medicine:");

        rackTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Rack");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(priceTxt)
                                    .addComponent(jLabel6)
                                    .addComponent(pidTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                    .addComponent(pnameTxt)
                                    .addComponent(catCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rackTxt)
                                    .addComponent(stockTxt)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(deleteProdBtn)
                                .addGap(77, 77, 77)
                                .addComponent(updateProdBtn))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(addProductBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(addProductBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rackTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateProdBtn)
                    .addComponent(deleteProdBtn))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("  Medicines  ", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(1220, 1030));

        addEmpBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addEmpBtn.setText("Add New Employee");
        addEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpBtnActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Phone No", "Email", "Designation", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.setGridColor(new java.awt.Color(153, 153, 153));
        jTable2.setRowHeight(22);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(250);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setPreferredWidth(80);
        }

        enameTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        ephoneTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        emailTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        salaryTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setText("Salary");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setText("Designation");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setText("Email ID");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setText("Phone No");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel16.setText("Employee Name");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setText("Employee ID");

        eidTxt.setEditable(false);
        eidTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        eidTxt.setToolTipText("Employee ID can't be modified");

        desigTxt.setEditable(false);
        desigTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        desigTxt.setToolTipText("Designation can't be modified");

        updateEmpBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        updateEmpBtn.setText("Update Employee");
        updateEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmpBtnActionPerformed(evt);
            }
        });

        deleteEmpBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deleteEmpBtn.setText("Delete Employee");
        deleteEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmpBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Update / Delete selected Employee:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addEmpBtn)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel12)))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(salaryTxt)
                                    .addComponent(eidTxt)
                                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(desigTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ephoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(deleteEmpBtn)
                        .addGap(77, 77, 77)
                        .addComponent(updateEmpBtn)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(addEmpBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(eidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(desigTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ephoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateEmpBtn)
                    .addComponent(deleteEmpBtn))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("  Employees  ", jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(1220, 1030));

        jTable3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name", "Phone No", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable3.setGridColor(new java.awt.Color(153, 153, 153));
        jTable3.setRowHeight(22);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable3.getColumnModel().getColumn(2).setResizable(false);
            jTable3.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTable3.getColumnModel().getColumn(3).setPreferredWidth(350);
        }

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setText("Supplier ID");

        sAddrTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        sidTxt.setEditable(false);
        sidTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sidTxt.setToolTipText("Supplier ID can't be modified");

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setText("Phone No");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setText("Supplier Name");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setText("Address");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Update / Delete selected Supplier:");

        sphoneTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        snameTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        addSupBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addSupBtn.setText("Add New Supplier");
        addSupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupBtnActionPerformed(evt);
            }
        });

        deleteSupBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deleteSupBtn.setText("Delete Supplier");
        deleteSupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSupBtnActionPerformed(evt);
            }
        });

        updateSupBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        updateSupBtn.setText("Update Supplier");
        updateSupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(snameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel19))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sAddrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sphoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(deleteSupBtn)
                                .addGap(77, 77, 77)
                                .addComponent(updateSupBtn))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addSupBtn)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(addSupBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(sidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sphoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(sAddrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateSupBtn)
                    .addComponent(deleteSupBtn))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("  Suppliers  ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void refreshProductTable(){
        try{
                model1.setRowCount(0);
                query = "SELECT * FROM medicine";
                rs = st.executeQuery(query);
                while(rs.next()){
                    int pid = rs.getInt("mid");
                    String pname = rs.getString("m_name");
                    int price = rs.getInt("price");
                    String category = rs.getString("category");
                    
                    query2 = "SELECT * FROM inventory WHERE mid = " + pid;
                    rs2 = st2.executeQuery(query2);
                    if(rs2.next()){
                    double stock = rs2.getDouble("stock");
                    String rack = rs2.getString("rack");
                    model1.addRow(new Object[]{pid,pname,category,rack,stock,price});
                    }
                }

            }
            catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                }
    }
    public static void setSelectedValue(JComboBox comboBox, String value)
    {
        String item;
        for (int i = 0; i < comboBox.getItemCount(); i++)
        {
            item = (String)comboBox.getItemAt(i);
            if (item.equalsIgnoreCase(value))
            {
                comboBox.setSelectedIndex(i);
                break;
            }
        }
    }
    
    void refreshEmpTable(){
        try{
            model2.setRowCount(0);
            query = "select * from employee";
            rs = st.executeQuery(query);
            while(rs.next()){
                int eid = rs.getInt("eid");
                String ename = rs.getString("e_name");
                String phone = rs.getString("e_phone");
                String email = rs.getString("email");
                String designation = rs.getString("designation");
                int salary = rs.getInt("salary");
                model2.addRow(new Object[]{eid,ename,phone,email,designation,salary});
            }
            
        }
        catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
            }
               
    }
    

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        refreshProductTable();
        refreshEmpTable();
        refreshSupplierTable();
    }//GEN-LAST:event_formWindowActivated

    private void updateSupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSupBtnActionPerformed
        // TODO add your handling code here:
        try{
            update = "UPDATE supplier SET s_name = ?, s_phone = ?, s_address = ?"
            + "WHERE sid = ?";
            pst = con.prepareStatement(update);
            pst.setString(1, snameTxt.getText());
            pst.setString(2, sphoneTxt.getText());
            pst.setString(3, sAddrTxt.getText());
            pst.setString(4, sidTxt.getText());
            int status = pst.executeUpdate();
            if(status>0){
                JOptionPane.showMessageDialog(rootPane, "Successfully updated Supplier", "Success", JOptionPane.INFORMATION_MESSAGE);

            }
            else
            JOptionPane.showMessageDialog(rootPane, "Could not update\nPlease select a supplier from the list", "Failed", JOptionPane.ERROR_MESSAGE);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_updateSupBtnActionPerformed

    private void deleteSupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSupBtnActionPerformed
        // TODO add your handling code here:
        if(sidTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Could not delete\nPlease select a supplier from the list", "Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int prompt = JOptionPane.showConfirmDialog(
            null, "This supplier will be permanently Deleted!\nProceed?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
        if (prompt == JOptionPane.YES_OPTION) {
            try{
                update = "DELETE FROM supplier WHERE sid = " + sidTxt.getText();
                int status = st.executeUpdate(update);
                if(status>0){
                    JOptionPane.showMessageDialog(rootPane, "Deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                JOptionPane.showMessageDialog(rootPane, "Could not delete\nPlease select a supplier from the list", "Failed", JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_deleteSupBtnActionPerformed

    private void addSupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupBtnActionPerformed
        // TODO add your handling code here:
        new AddSupplier().setVisible(true);
    }//GEN-LAST:event_addSupBtnActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        int i = jTable3.getSelectedRow();
        sidTxt.setText(model3.getValueAt(i, 0).toString());
        snameTxt.setText(model3.getValueAt(i, 1).toString());
        sphoneTxt.setText(model3.getValueAt(i, 2).toString());
        sAddrTxt.setText(model3.getValueAt(i, 3).toString());
    }//GEN-LAST:event_jTable3MouseClicked

    private void deleteEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmpBtnActionPerformed
        // TODO add your handling code here:
        if(desigTxt.getText().equals("SalesPerson")){
            int prompt = JOptionPane.showConfirmDialog(
                null, "This employee will be permanently Deleted!\nProceed?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);
            if (prompt == JOptionPane.YES_OPTION) {
                try{
                    update = "DELETE FROM employee WHERE eid = " + eidTxt.getText();
                    int status = st.executeUpdate(update);
                    if(status>0){
                        JOptionPane.showMessageDialog(rootPane, "Deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else
                    JOptionPane.showMessageDialog(rootPane, "Could not delete\nPlease select an employee from the list", "Failed", JOptionPane.ERROR_MESSAGE);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }
        else if (desigTxt.getText().equals("Manager"))
        JOptionPane.showMessageDialog(rootPane, "You cannot delete a Manager!", "Failed", JOptionPane.ERROR_MESSAGE);
        else
        JOptionPane.showMessageDialog(rootPane, "Select an employee from the list", "Failed", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_deleteEmpBtnActionPerformed

    private void updateEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmpBtnActionPerformed
        // TODO add your handling code here:
        try{
            update = "UPDATE employee SET e_name = ?, e_phone = ?, email = ?, salary = ?"
            + "WHERE eid = ?";
            pst = con.prepareStatement(update);
            pst.setString(1, enameTxt.getText());
            pst.setString(2, ephoneTxt.getText());
            pst.setString(3, emailTxt.getText());
            pst.setString(4, salaryTxt.getText());
            pst.setString(5, eidTxt.getText());
            int status = pst.executeUpdate();
            if(status>0){
                JOptionPane.showMessageDialog(rootPane, "Successfully updated Employee", "Success", JOptionPane.INFORMATION_MESSAGE);

            }
            else
            JOptionPane.showMessageDialog(rootPane, "Could not update\nPlease select an employee from the list", "Failed", JOptionPane.ERROR_MESSAGE);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_updateEmpBtnActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        eidTxt.setText(model2.getValueAt(i, 0).toString());
        enameTxt.setText(model2.getValueAt(i, 1).toString());
        ephoneTxt.setText(model2.getValueAt(i, 2).toString());
        emailTxt.setText(model2.getValueAt(i, 3).toString());
        desigTxt.setText(model2.getValueAt(i, 4).toString());
        salaryTxt.setText(model2.getValueAt(i, 5).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void addEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpBtnActionPerformed
        // TODO add your handling code here:
        new AddEmp().setVisible(true);
    }//GEN-LAST:event_addEmpBtnActionPerformed

    private void updateProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProdBtnActionPerformed
        // TODO add your handling code here:
        try{
            update = "UPDATE medicine SET m_name = ?, category = ?, price = ?"
            + "WHERE mid = ?";
            pst = con.prepareStatement(update);
            pst.setString(1, pnameTxt.getText());
            pst.setString(2, catCombo.getSelectedItem().toString());
            pst.setString(3, priceTxt.getText());
            pst.setString(4, pidTxt.getText());
            int status = pst.executeUpdate();

            update = "UPDATE inventory SET rack = ? WHERE mid = ?";
            pst = con.prepareStatement(update);
            pst.setString(1, rackTxt.getText());
            pst.setString(2, pidTxt.getText());
            int status1 = pst.executeUpdate();

            if(status>0 && status1>0){
                JOptionPane.showMessageDialog(rootPane, "Successfully updated Medicine", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            JOptionPane.showMessageDialog(rootPane, "Could not update\nPlease select a Medicine from the list", "Failed", JOptionPane.ERROR_MESSAGE);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_updateProdBtnActionPerformed

    private void deleteProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProdBtnActionPerformed
        // TODO add your handling code here:
        if(pidTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Could not delete\nPlease select a medicine from the list", "Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int prompt = JOptionPane.showConfirmDialog(
            null, "This medicine will be permanently Deleted!\nProceed?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
        if (prompt == JOptionPane.YES_OPTION) {
            try{
                update = "DELETE FROM medicine WHERE mid = " + pidTxt.getText();
                int status = st.executeUpdate(update);
                if(status>0){
                    JOptionPane.showMessageDialog(rootPane, "Deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                JOptionPane.showMessageDialog(rootPane, "Could not delete\nPlease select a medicine from the list", "Failed", JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_deleteProdBtnActionPerformed

    private void addProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductBtnActionPerformed

        new AddMedicine().setVisible(true);

    }//GEN-LAST:event_addProductBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        pidTxt.setText(model1.getValueAt(i, 0).toString());
        pnameTxt.setText(model1.getValueAt(i, 1).toString());
        setSelectedValue(catCombo, model1.getValueAt(i, 2).toString());
        rackTxt.setText(model1.getValueAt(i,3).toString());
        stockTxt.setText(model1.getValueAt(i, 4).toString());
        priceTxt.setText(model1.getValueAt(i, 5).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    void refreshSupplierTable(){
        try{
            model3.setRowCount(0);
            query = "select * from supplier";
            rs = st.executeQuery(query);
            while(rs.next()){
                int sid = rs.getInt("sid");
                String sname = rs.getString("s_name");
                String phone = rs.getString("s_phone");
                String address = rs.getString("s_address");
                model3.addRow(new Object[]{sid,sname,phone,address});
            }
            
        }
        catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
            }
    }
    
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmpBtn;
    private javax.swing.JButton addProductBtn;
    private javax.swing.JButton addSupBtn;
    private javax.swing.JComboBox<String> catCombo;
    private javax.swing.JButton deleteEmpBtn;
    private javax.swing.JButton deleteProdBtn;
    private javax.swing.JButton deleteSupBtn;
    private javax.swing.JTextField desigTxt;
    private javax.swing.JTextField eidTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField enameTxt;
    private javax.swing.JTextField ephoneTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField pidTxt;
    private javax.swing.JTextField pnameTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField rackTxt;
    private javax.swing.JTextField sAddrTxt;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JTextField sidTxt;
    private javax.swing.JTextField snameTxt;
    private javax.swing.JTextField sphoneTxt;
    private javax.swing.JTextField stockTxt;
    private javax.swing.JButton updateEmpBtn;
    private javax.swing.JButton updateProdBtn;
    private javax.swing.JButton updateSupBtn;
    // End of variables declaration//GEN-END:variables
}
